default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tgs_development

test:
  <<: *default
  database: tgs_test

production:
  <<: *default
  database: tgs_production

